export enum OrderStatus {
  PENDING = "PENDING",
  SHIPPED = "SHIPPED",
  DELIVERED = "DELIVERED",
  RETURNED = "RETURNED",
  REFUNDED = "REFUNDED",
  REVIEWED = "REVIEWED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED"

}
